// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMPkWS8jcPVYJKXK1jVFTACHUstsmrfAE',
    appId: '1:492187942103:web:144bc92937bb1869e74492',
    messagingSenderId: '492187942103',
    projectId: 'fgi-y2g-development',
    authDomain: 'fgi-y2g-development.firebaseapp.com',
    storageBucket: 'fgi-y2g-development.appspot.com',
    measurementId: 'G-7W4JLGBZ38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRVgSByTFC4CeJwmfhQs0dYDluxhKAEbw',
    appId: '1:492187942103:android:e9298dc8fa6aada3e74492',
    messagingSenderId: '492187942103',
    projectId: 'fgi-y2g-development',
    storageBucket: 'fgi-y2g-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFF2ImllfOWn7s7aLeFKsUYQOjLfz2jgk',
    appId: '1:492187942103:ios:d2adc3d2bcddd700e74492',
    messagingSenderId: '492187942103',
    projectId: 'fgi-y2g-development',
    storageBucket: 'fgi-y2g-development.appspot.com',
    iosBundleId: 'com.example.fgiY2j',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFF2ImllfOWn7s7aLeFKsUYQOjLfz2jgk',
    appId: '1:492187942103:ios:ff646d3f02d8e4ede74492',
    messagingSenderId: '492187942103',
    projectId: 'fgi-y2g-development',
    storageBucket: 'fgi-y2g-development.appspot.com',
    iosBundleId: 'com.example.fgiY2j.RunnerTests',
  );
}
